import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import { ThemeProvider } from "@/components/theme-provider"
import { SiteHeader } from "@/components/site-header"

import { AuthContextProvider } from '../../context/authContext'
 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UNLISTED STOCKS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthContextProvider>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="">
                  <SiteHeader />
                  
                          {children}
                       
                  {/* <Footer /> */}
                </div>
          </ThemeProvider>
        </body>
        </AuthContextProvider>
    </html>
  )
}
